[package]
name = "pinky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.18", features = ["derive"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
tempfile = "3"
sha2 = "0.10.2"
hex = "0.4"
semver = "1.0.10"
