#!/bin/bash
set -euo pipefail

. $(dirname $0)/functions.sh

init_system_vars

if [ "$OS_NAME" = "linux" ]; then
    export RUSTFLAGS='-C target-feature=+crt-static'
fi

cargo build --verbose --release
